% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\pagenumbering{gobble}

\begin{titlepage}
\centering
\vspace*{1cm}

\includegraphics[width=0.35\textwidth]{img/uib.png}\par
\vspace{1.5cm}

{\LARGE\bfseries 21746 - Data Mining\par}
\vspace{0.3cm}
{\LARGE\bfseries Final Project\par}
\vspace{0.8cm}
{\Large Steam Successful Indie Games Study\par}

\vspace{1.8cm}

{\large
Iván Pulgar Rodas\\
Jordi Sevilla Marí\\
Nahuel Vazquez\\
Yelyzaveta Denysova\\
Xiaozhe Cheng\\
Gabriel Oliver Artigues\\
Arturo Mus Mejías\par}

\vfill
{\large 2026-01-10\par}
\end{titlepage}

\clearpage
\pagenumbering{gobble}
\tableofcontents
\clearpage

\pagenumbering{arabic}
\setcounter{page}{1}

\section{Introduction}\label{introduction}

\subsection{Explanation of the
Attributes}\label{explanation-of-the-attributes}

The dataset we will be working with contains a total number of 94948
observations and 47 columns or variables. The columns that will be used
are described bellow:

\begin{itemize}
\tightlist
\item
  \textbf{\texttt{appid}}: Unique idetnifier of the game on Steam.
  {[}num{]}
\item
  \textbf{\texttt{name}}: Name of the game. {[}text{]}
\item
  \textbf{`released\_date``}: Represents the date where the game was
  released. {[}time{]}
\item
  \textbf{`required\_age``}: Corresponds to the minimum age required to
  play the game. {[}num{]}
\item
  \textbf{\texttt{price}}: How much the game costs. If its 0 it means
  that the game is Free to Play. {[}num{]}
\item
  \textbf{\texttt{dlc\_count}}: Ammount of DLCs (Downloadable Contents)
  the game has. {[}num{]}
\item
  \textbf{\texttt{suppport\_url}}: URL to the support page of the game.
  {[}text{]}
\item
  \textbf{\texttt{windows}}: Determines if the game runs in windows.
  {[}categorical{]}
\item
  \textbf{\texttt{mac}}: Determines if the game runs in mac.
  {[}categorical{]}
\item
  \textbf{\texttt{linux}}: Determines if the game runs in linux.
  {[}categorical{]}
\item
  \textbf{\texttt{metacritic\_score}}: Metacritic score based on
  critcical reviews (reviews from professionalss). By performing an
  investigation we think that an score of 0 means that when the scraping
  of the data was done there where no reviews for that game yet.
  {[}num{]}
\item
  \textbf{\texttt{achievements}}: Number of achievements the game has.
  {[}num{]}
\item
  \textbf{`recommendations``}: Ammount of user recommendations.
  {[}num{]}
\item
  \textbf{\texttt{supported\_languages}}: List of languages that the
  game supports.{[}\textbf{NO SÉ QUE CATEGORÍA DARLE}{]}
\item
  \textbf{\texttt{packages}}: Avaliable packages for the game. It
  contains the name and a description of the package and the names,
  descriptions and subprices of the subpackages. {[}\textbf{LO MISMO QUE
  ARRIBA}{]}
\item
  \textbf{\texttt{Developers}}: List of developers associated with the
  game. {[}\textbf{LO MISMO QUE ARRIBA}{]}
\item
  \textbf{\texttt{publishers}}: List of publishers associated with the
  game. {[}\textbf{LO MISMO QUE ARRIBA}{]}
\item
  \textbf{\texttt{categories}}: List of categories that the game has.
  {[}\textbf{LO MISMO QUE ARRIBA}{]}
\item
  \textbf{\texttt{genres}}: List of genres that the game belongs to.
  {[}\textbf{LO MISMO QUE ARRIBA}{]}
\item
  \textbf{\texttt{positive}}: Ammount of positive votes the game has.
  {[}num{]}
\item
  \textbf{\texttt{negative}}: Ammount of negative votes the game has.
  {[}num{]}
\item
  \textbf{\texttt{estimated\_owners}}: Estimated owners of the game.
  {[}text{]}
\item
  \textbf{\texttt{average\_playtime\_forever}}: Average playtime since
  March 2009 measured in minutes. {[}num{]}
\item
  \textbf{\texttt{average\_playtime\_2weeks}}: Average playtime in the
  last two weeks measured in minutes. {[}num{]}
\item
  \textbf{\texttt{median\_playtime\_forever}}: Median playtime since
  March 2009 measured in minutes. {[}num{]}
\item
  \textbf{\texttt{median\_playtime\_2weeks}}: Median playtime in the
  last two weeks measured in minutes.{[}num{]}
\item
  \textbf{\texttt{peak\_ccu}}: Number of current users playing the day
  before the data was scrapped. {[}num{]}
\item
  \textbf{\texttt{tags}}: List of tags the game has with its name and
  its key. {[}\textbf{NO SE QUE CATEGORIA DARLE}{]}
\item
  \textbf{\texttt{pct\_pos\_total}}: Percentage of all reviews that are
  positive. {[}num{]}
\item
  \textbf{\texttt{num\_reviews\_total}}: Nummber of the total reviews
  the game has. {[}num{]}
\end{itemize}

\subsection{Objectives}\label{objectives}

\textbf{TODO: ADD OBJECTIVES OF STUDY}

\section{Procesing de data}\label{procesing-de-data}

General look of the dataset

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(steam)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      appid             name           release_date        required_age    
##  Min.   :     20   Length:94948       Length:94948       Min.   :-1.0000  
##  1st Qu.: 887338   Class :character   Class :character   1st Qu.: 0.0000  
##  Median :1591145   Mode  :character   Mode  :character   Median : 0.0000  
##  Mean   :1707530                                         Mean   : 0.1783  
##  3rd Qu.:2491702                                         3rd Qu.: 0.0000  
##  Max.   :3570420                                         Max.   :21.0000  
##                                                                           
##      price            dlc_count         detailed_description about_the_game    
##  Min.   :   0.000   Min.   :   0.0000   Length:94948         Length:94948      
##  1st Qu.:   0.990   1st Qu.:   0.0000   Class :character     Class :character  
##  Median :   3.990   Median :   0.0000   Mode  :character     Mode  :character  
##  Mean   :   6.911   Mean   :   0.5632                                          
##  3rd Qu.:   9.990   3rd Qu.:   0.0000                                          
##  Max.   : 999.980   Max.   :3427.0000                                          
##                                                                                
##  short_description    reviews          header_image         website         
##  Length:94948       Length:94948       Length:94948       Length:94948      
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##  support_url        support_email        windows              mac           
##  Length:94948       Length:94948       Length:94948       Length:94948      
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##     linux           metacritic_score metacritic_url      achievements    
##  Length:94948       Min.   : 0.000   Length:94948       Min.   :   0.00  
##  Class :character   1st Qu.: 0.000   Class :character   1st Qu.:   0.00  
##  Mode  :character   Median : 0.000   Mode  :character   Median :   2.00  
##                     Mean   : 2.764                      Mean   :  19.54  
##                     3rd Qu.: 0.000                      3rd Qu.:  19.00  
##                     Max.   :97.000                      Max.   :9821.00  
##                                                                          
##  recommendations      notes           supported_languages full_audio_languages
##  Min.   :      0   Length:94948       Length:94948        Length:94948        
##  1st Qu.:      0   Class :character   Class :character    Class :character    
##  Median :      0   Mode  :character   Mode  :character    Mode  :character    
##  Mean   :   1022                                                              
##  3rd Qu.:      0                                                              
##  Max.   :4401572                                                              
##                                                                               
##    packages          developers         publishers         categories       
##  Length:94948       Length:94948       Length:94948       Length:94948      
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##     genres          screenshots           movies            user_score       
##  Length:94948       Length:94948       Length:94948       Min.   :  0.00000  
##  Class :character   Class :character   Class :character   1st Qu.:  0.00000  
##  Mode  :character   Mode  :character   Mode  :character   Median :  0.00000  
##                                                           Mean   :  0.03097  
##                                                           3rd Qu.:  0.00000  
##                                                           Max.   :100.00000  
##                                                                              
##    score_rank        positive          negative         estimated_owners  
##  Min.   : 98.00   Min.   :      0   Min.   :      0.0   Length:94948      
##  1st Qu.: 99.00   1st Qu.:      0   1st Qu.:      0.0   Class :character  
##  Median : 99.00   Median :      8   Median :      2.0   Mode  :character  
##  Mean   : 99.13   Mean   :   1218   Mean   :    202.1                     
##  3rd Qu.:100.00   3rd Qu.:     51   3rd Qu.:     15.0                     
##  Max.   :100.00   Max.   :7480813   Max.   :1135108.0                     
##  NA's   :94909                                                            
##  average_playtime_forever average_playtime_2weeks median_playtime_forever
##  Min.   :      0.0        Min.   :    0.000       Min.   :      0.0      
##  1st Qu.:      0.0        1st Qu.:    0.000       1st Qu.:      0.0      
##  Median :      0.0        Median :    0.000       Median :      0.0      
##  Mean   :    108.6        Mean   :    4.757       Mean   :    108.4      
##  3rd Qu.:      0.0        3rd Qu.:    0.000       3rd Qu.:      0.0      
##  Max.   :1462997.0        Max.   :18568.000       Max.   :1462997.0      
##                                                                          
##  median_playtime_2weeks    discount          peak_ccu        
##  Min.   :    0.000      Min.   :  0.000   Min.   :0.000e+00  
##  1st Qu.:    0.000      1st Qu.:  0.000   1st Qu.:0.000e+00  
##  Median :    0.000      Median :  0.000   Median :0.000e+00  
##  Mean   :    5.018      Mean   :  4.307   Mean   :9.285e+01  
##  3rd Qu.:    0.000      3rd Qu.:  0.000   3rd Qu.:0.000e+00  
##  Max.   :18568.000      Max.   :100.000   Max.   :1.212e+06  
##                                                              
##      tags           pct_pos_total    num_reviews_total pct_pos_recent   
##  Length:94948       Min.   : -1.00   Min.   :     -1   Min.   : -1.000  
##  Class :character   1st Qu.: -1.00   1st Qu.:     -1   1st Qu.: -1.000  
##  Mode  :character   Median : 58.00   Median :     15   Median : -1.000  
##                     Mean   : 44.63   Mean   :   1448   Mean   :  5.328  
##                     3rd Qu.: 84.00   3rd Qu.:     80   3rd Qu.: -1.000  
##                     Max.   :100.00   Max.   :8632939   Max.   :100.000  
##                                                                         
##  num_reviews_recent
##  Min.   :   -1.00  
##  1st Qu.:   -1.00  
##  Median :   -1.00  
##  Mean   :   16.88  
##  3rd Qu.:   -1.00  
##  Max.   :96473.00  
## 
\end{verbatim}

Explanation of first looks of it, bad formatting, NA's, negative
values\ldots{}

\subsection{Handling of NA values}\label{handling-of-na-values}

The attributes with missing values are:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{na\_counts }\OtherTok{\textless{}{-}}\NormalTok{ steam }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summarise\_all}\NormalTok{(}\SpecialCharTok{\textasciitilde{}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(.)))}

\FunctionTok{print}\NormalTok{(na\_counts)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   appid name release_date required_age price dlc_count detailed_description
## 1     0    0            0            0     0         0                    0
##   about_the_game short_description reviews header_image website support_url
## 1              0                 0       0            0       0           0
##   support_email windows mac linux metacritic_score metacritic_url achievements
## 1             0       0   0     0                0              0            0
##   recommendations notes supported_languages full_audio_languages packages
## 1               0     0                   0                    0        0
##   developers publishers categories genres screenshots movies user_score
## 1          0          0          0      0           0      0          0
##   score_rank positive negative estimated_owners average_playtime_forever
## 1      94909        0        0                0                        0
##   average_playtime_2weeks median_playtime_forever median_playtime_2weeks
## 1                       0                       0                      0
##   discount peak_ccu tags pct_pos_total num_reviews_total pct_pos_recent
## 1        0        0    0             0                 0              0
##   num_reviews_recent
## 1                  0
\end{verbatim}

The columns with missing values are as follows:

LOs juegos con número de reseñas = -1 creemos que son porque el
scrappear ha fallado durante su ejecución. Si vamos a trabajar con las
reseñas podríamos decir en la presentación que vamos a probar de volver
a intentar scrappear la información

\begin{verbatim}
## tibble [88,982 x 30] (S3: tbl_df/tbl/data.frame)
##  $ appid                   : int [1:88982] 2556940 449940 1287250 866510 870990 439260 388390 2243560 1908870 3165610 ...
##  $ name                    : chr [1:88982] "! Shakabula *" "! That Bastard Is Trying To Steal Our Gold !" "! Wild Russia !" "!AnyWay!" ...
##  $ release_date            : Date[1:88982], format: "2023-10-13" "2016-03-03" ...
##  $ required_age            : int [1:88982] 0 0 0 0 0 0 0 0 0 0 ...
##  $ price                   : num [1:88982] 14.99 2.99 19.99 1.99 0.99 ...
##  $ dlc_count               : int [1:88982] 0 0 0 39 0 0 0 1 3 0 ...
##  $ windows                 : chr [1:88982] "True" "True" "True" "True" ...
##  $ mac                     : chr [1:88982] "False" "False" "False" "False" ...
##  $ linux                   : chr [1:88982] "False" "True" "False" "False" ...
##  $ metacritic_score        : int [1:88982] 0 0 0 0 0 0 0 0 0 0 ...
##  $ achievements            : int [1:88982] 0 0 9 4997 2021 0 0 19 13 5 ...
##  $ recommendations         : int [1:88982] 0 0 0 495 0 0 0 108 0 0 ...
##  $ supported_languages     : chr [1:88982] "['English']" "['English']" "['English', 'Simplified Chinese', 'Russian']" "['English', 'Russian', 'French', 'Italian', 'German', 'Polish', 'Ukrainian', 'Swedish', 'Simplified Chinese', '"| __truncated__ ...
##  $ packages                : chr [1:88982] "[{'title': 'Buy ! Shakabula *', 'description': '', 'subs': [{'text': '! Shakabula * - $14.99', 'description': '"| __truncated__ "[{'title': 'Buy ! That Bastard Is Trying To Steal Our Gold !', 'description': '', 'subs': [{'text': '! That Bas"| __truncated__ "[{'title': 'Buy ! Wild Russia !', 'description': '', 'subs': [{'text': 'Wild Russia - $19.99', 'description': '"| __truncated__ "[{'title': 'Buy !AnyWay!', 'description': '', 'subs': [{'text': '!AnyWay! - $1.99', 'description': '', 'price':"| __truncated__ ...
##  $ developers              : chr [1:88982] "['Skermunkel']" "['WTFOMGames']" "['Andreev Worlds']" "['EYEFRONT']" ...
##  $ publishers              : chr [1:88982] "['Skermunkel']" "['WTFOMGames']" "['Andreev Worlds']" "['EYEFRONT']" ...
##  $ categories              : chr [1:88982] "['Single-player', 'Full controller support', 'Steam Cloud', 'Family Sharing']" "['Single-player', 'Steam Trading Cards', 'Partial Controller Support', 'Family Sharing']" "['Single-player', 'Steam Achievements', 'Partial Controller Support', 'Family Sharing']" "['Single-player', 'Multi-player', 'Steam Achievements', 'Full controller support', 'Steam Trading Cards', 'Stea"| __truncated__ ...
##  $ genres                  : chr [1:88982] "['Action', 'Indie', 'RPG', 'Early Access']" "['Action', 'Adventure', 'Casual', 'Indie']" "['Action', 'Adventure', 'Casual']" "['Adventure', 'Casual', 'Indie']" ...
##  $ positive                : int [1:88982] 0 57 45 410 25 83 37 126 0 0 ...
##  $ negative                : int [1:88982] 4 78 34 180 32 18 102 10 0 0 ...
##  $ average_playtime_forever: int [1:88982] 0 312 0 360 0 0 244 0 0 0 ...
##  $ average_playtime_2weeks : int [1:88982] 0 0 0 0 0 0 0 0 0 0 ...
##  $ median_playtime_forever : int [1:88982] 0 391 0 378 0 0 244 0 0 0 ...
##  $ median_playtime_2weeks  : int [1:88982] 0 0 0 0 0 0 0 0 0 0 ...
##  $ peak_ccu                : int [1:88982] 0 0 0 6 0 0 0 0 0 0 ...
##  $ tags                    : chr [1:88982] "{'Early Access': 213, 'Action': 193, 'RPG': 187, 'JRPG': 184, 'Shooter': 181, 'Bullet Hell': 178, 'Metroidvania"| __truncated__ "{'Puzzle-Platformer': 237, 'Dark Humor': 233, 'Dungeon Crawler': 228, 'Mining': 225, 'Memes': 223, 'Destruction"| __truncated__ "{'Adventure': 57, 'Action': 56, 'Casual': 56, 'Horror': 13, 'Post-apocalyptic': 13, 'Atmospheric': 12}" "{'Side Scroller': 179, 'Precision Platformer': 173, '2D Platformer': 170, 'Casual': 166, 'Sandbox': 163, 'Platf"| __truncated__ ...
##  $ pct_pos_total           : int [1:88982] -1 55 61 71 55 82 55 91 95 66 ...
##  $ num_reviews_total       : int [1:88982] -1 68 62 495 18 101 20 108 281 12 ...
##  $ estimated_owners_min    : int [1:88982] 0 50000 0 100000 0 0 100000 20000 0 0 ...
##  $ estimated_owners_max    : int [1:88982] 20000 100000 20000 200000 20000 20000 200000 50000 0 0 ...
\end{verbatim}

\begin{verbatim}
##      appid             name            release_date         required_age    
##  Min.   :     20   Length:88982       Min.   :1997-06-30   Min.   :-1.0000  
##  1st Qu.: 852782   Class :character   1st Qu.:2018-12-05   1st Qu.: 0.0000  
##  Median :1522535   Mode  :character   Median :2021-10-29   Median : 0.0000  
##  Mean   :1655079                      Mean   :2021-04-04   Mean   : 0.1826  
##  3rd Qu.:2429338                      3rd Qu.:2023-12-14   3rd Qu.: 0.0000  
##  Max.   :3542350                      Max.   :2025-03-10   Max.   :21.0000  
##      price            dlc_count           windows              mac           
##  Min.   :   0.000   Min.   :   0.0000   Length:88982       Length:88982      
##  1st Qu.:   0.990   1st Qu.:   0.0000   Class :character   Class :character  
##  Median :   4.990   Median :   0.0000   Mode  :character   Mode  :character  
##  Mean   :   7.349   Mean   :   0.5957                                        
##  3rd Qu.:   9.990   3rd Qu.:   0.0000                                        
##  Max.   : 999.980   Max.   :3427.0000                                        
##     linux           metacritic_score  achievements     recommendations  
##  Length:88982       Min.   : 0.00    Min.   :   0.00   Min.   :      0  
##  Class :character   1st Qu.: 0.00    1st Qu.:   0.00   1st Qu.:      0  
##  Mode  :character   Median : 0.00    Median :   5.00   Median :      0  
##                     Mean   : 2.91    Mean   :  20.67   Mean   :   1013  
##                     3rd Qu.: 0.00    3rd Qu.:  20.00   3rd Qu.:      0  
##                     Max.   :97.00    Max.   :9821.00   Max.   :4401572  
##  supported_languages   packages          developers         publishers       
##  Length:88982        Length:88982       Length:88982       Length:88982      
##  Class :character    Class :character   Class :character   Class :character  
##  Mode  :character    Mode  :character   Mode  :character   Mode  :character  
##                                                                              
##                                                                              
##                                                                              
##   categories           genres             positive          negative        
##  Length:88982       Length:88982       Min.   :      0   Min.   :      0.0  
##  Class :character   Class :character   1st Qu.:      1   1st Qu.:      0.0  
##  Mode  :character   Mode  :character   Median :     10   Median :      2.0  
##                                        Mean   :   1267   Mean   :    208.3  
##                                        3rd Qu.:     59   3rd Qu.:     17.0  
##                                        Max.   :7480813   Max.   :1135108.0  
##  average_playtime_forever average_playtime_2weeks median_playtime_forever
##  Min.   :      0.0        Min.   :    0.000       Min.   :      0.0      
##  1st Qu.:      0.0        1st Qu.:    0.000       1st Qu.:      0.0      
##  Median :      0.0        Median :    0.000       Median :      0.0      
##  Mean   :    115.6        Mean   :    4.998       Mean   :    115.5      
##  3rd Qu.:      0.0        3rd Qu.:    0.000       3rd Qu.:      0.0      
##  Max.   :1462997.0        Max.   :18568.000       Max.   :1462997.0      
##  median_playtime_2weeks    peak_ccu             tags           pct_pos_total   
##  Min.   :    0.000      Min.   :0.000e+00   Length:88982       Min.   : -1.00  
##  1st Qu.:    0.000      1st Qu.:0.000e+00   Class :character   1st Qu.: -1.00  
##  Median :    0.000      Median :0.000e+00   Mode  :character   Median : 60.00  
##  Mean   :    5.277      Mean   :9.778e+01                      Mean   : 45.39  
##  3rd Qu.:    0.000      3rd Qu.:0.000e+00                      3rd Qu.: 84.00  
##  Max.   :18568.000      Max.   :1.212e+06                      Max.   :100.00  
##  num_reviews_total estimated_owners_min estimated_owners_max
##  Min.   :     -1   Min.   :        0    Min.   :        0   
##  1st Qu.:     -1   1st Qu.:        0    1st Qu.:    20000   
##  Median :     15   Median :        0    Median :    20000   
##  Mean   :   1320   Mean   :    59038    Mean   :   143056   
##  3rd Qu.:     81   3rd Qu.:        0    3rd Qu.:    20000   
##  Max.   :8632939   Max.   :200000000    Max.   :500000000
\end{verbatim}

\section{Exploratory Data Analysis}\label{exploratory-data-analysis}

Now we going to explore the market share of each genre and how it
evolves through time, and the playtime of each genre trying to see which
are the genres with more hardcore players.

Firstly for having a objective view if the genre have truly grown we
going to mesure the market share of each genre of each year. The
advantage of using this is that the grown of each year is relative to
the total grown of the game industry, if we use the raw game numbers we
cannot difference if the game have actually grown or it's because the
general game market have a growing tendency.

\[
\tex{Market Share} = \frac{\tex{Genre Games}}{\tex{Total Games}}
\]

Now let's define some metrics to determine the performance and behaviour
of the genres.

\[
\tex{Net Growth} = \text{Market Share}_\text{final} - \text{Market Share}_{initial}
\]

\[
\tex{Volatility} = \Sum \abs{\delta \text{Market Share}}
\]

\begin{verbatim}
## # A tibble: 14 x 3
##    Genre       Total_Volatility Net_Growth
##    <chr>                  <dbl>      <dbl>
##  1 action                  54.0     10.8  
##  2 casual                  43.6     15.8  
##  3 platformer              41.4      8.51 
##  4 tabletop                36.6    -12.3  
##  5 strategy                28.8     -8.60 
##  6 shooter                 27.6     -0.703
##  7 RPG                     23.7      9.25 
##  8 fighting                19.3      2.04 
##  9 simulation              18.1      2.60 
## 10 horror                  15.4      5.90 
## 11 sport                   13.8      0.224
## 12 walking_sim             13.7      2.64 
## 13 roguelike               13.2      8.59 
## 14 music                   10.3     -2.58
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-12-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{positive\_genres }\OtherTok{\textless{}{-}}\NormalTok{ genre\_grow }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(Net\_Growth }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pull}\NormalTok{(Genre)}
\NormalTok{negative\_genres }\OtherTok{\textless{}{-}}\NormalTok{ genre\_grow }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(Net\_Growth }\SpecialCharTok{\textless{}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pull}\NormalTok{(Genre)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-14-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-15-1.pdf}}

\begin{verbatim}
## # A tibble: 14 x 4
##    Genre_Group Mean_Playtime Median_Playtime Total_Games
##    <chr>               <dbl>           <dbl>       <int>
##  1 fighting            1300.            308          689
##  2 roguelike            781.            300          624
##  3 strategy             974.            290         2526
##  4 RPG                 2024.            288         2851
##  5 simulation          2071.            247         2292
##  6 action              1137.            236.        5062
##  7 shooter             1204.            232         1397
##  8 horror              1841.            214.        1238
##  9 platformer           517.            204.        1194
## 10 tabletop             784.            196         2033
## 11 casual              1513.            184.        3164
## 12 sport                680.            172.         700
## 13 walking_sim          446.            156.         340
## 14 music               5768.            152          196
\end{verbatim}

\begin{verbatim}
## [1] 7981
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-20-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-21-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-23-1.pdf}}

\section{Commonalities among successful indie
games}\label{commonalities-among-successful-indie-games}

Indie game development is high-risk: budgets are limited, marketing
reach is uncertain, and audience discovery can be unpredictable. This
section explores commonalities across successful indie games, with two
practical goals: * \textbf{Understand market audience:} identify what
combinations of genres/mechanics tend to co-occur among games that reach
larger audiences. * \textbf{Reduce risk for game-making:} extract
patterns that can guide design decisions without prescribing a single
``correct'' formula.

We focus on four questions: * \textbf{Does genre matter?} * \textbf{Do
mechanics matter (especially in combination with genre)?} * \textbf{Do
game characteristics matter (e.g., camera, player modes, VR)?} *
\textbf{Does pricing matter (relationship with owners)?}

\subsection{Selecting indie games}\label{selecting-indie-games}

Steam has done the hard work for us by including ``Indie'' as a
genre/tag (and related tags such as ``Crowdfunded'' / ``Kickstarter'').
Given that these tags have been assigned by users world-wide, we can
agree on these tags representing widely-considered indie games. We
filter the dataset to games containing any of these signals in Genres,
Tags or Categories.

\subsection{Determining ``successful'' indie
games}\label{determining-successful-indie-games}

Determining ``successful'' indie games

``Success'' is not directly labeled in the dataset, so we build an
operational proxy based on market and engagement signals. The main goal
of this step is to isolate a subset of indie games that consistently
perform better than the rest, so that later sections (association rules
and plots) focus on patterns that appear among higher-impact titles.

\subsubsection{Clustering approach}\label{clustering-approach}

We cluster indie games using a set of numeric variables that capture
outcomes and engagement (e.g., recommendations, reviews, playtime, peak
CCU, owners/revenue estimates, price, and platform availability). Before
fixing the final configuration, we experimented with multiple numbers of
clusters: * \textbf{2 clusters} (attempting to represent successful vs
not successful) * \textbf{3 clusters} (attempting to represent massively
successful, successful and not successful) * \textbf{4 clusters} *
\textbf{5 clusters} * \textbf{10 clusters}

The best segmentation for interpretability and separation was obtained
with 3 clusters.

In our dataset, representative examples of these mid/high clusters
included games such as Deceit, Graveyard Keeper, Unturned (mid-tier),
and Stardew Valley, Subnautica, Terraria (top-tier). These examples
illustrate how the clustering captures meaningful outcome tiers rather
than arbitrary partitions.

We implement the final clustering using k-means with k = 3 on
standardized variables.

Using this proxy, 37,791 games are labeled successful (57.8\% of indie
games).

\subsubsection{Validation: do clusters separate
meaningfully?}\label{validation-do-clusters-separate-meaningfully}

Because clustering is unsupervised, we validate quality using a simple
but practical hypothesis: \emph{If the most discriminant variable is
unable to separate the clusters, then the clustering is likely not
meaningful.} We therefore compute the variable that best differentiates
the clusters (highest ANOVA F-statistic) and verify that it produces a
clear separation across groups.

In our case, the most discriminant variable is pct\_pos\_total and it
produces a clean ordering between the three clusters, which supports
using this partition in the rest of the report.

As an additional sanity check, we compute a global silhouette score on a
random sample of games in the standardized feature space. Silhouette
values closer to 1 indicate well-separated clusters, values near 0
indicate overlap, and negative values suggest poor assignments.

The average silhouette score on the sample is 0.377.

\subsubsection{Cluster interpretation}\label{cluster-interpretation}

The figure below summarizes the mean and median values of the
discriminant variable (pct\_pos\_total) across clusters, alongside the
number of games per tier.

In our run, the discriminant variable is pct\_pos\_total, which acts as
a strong quality/visibility signal: the unsuccessful long-tail cluster
concentrates near the lowest values, while the two top-tier cluster
achieves the highest values, separating games with limited traction from
games with stable success.
\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-27-1.pdf}}
A key takeaway from the cluster sizes is that the distribution is highly
imbalanced: a large share of games are concentrated in the lower-to-mid
tiers, while the top tier contains only a small number of games. In this
run, the lowest tier accounts for , whereas the highest tier represents
only of indie games.
\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-28-1.pdf}}
Since the clusters are interpretable and separable (both visually and by
the discriminant variable test), we use them to define a successful
subset and proceed with pattern mining in the next sections.

\subsection{Genre study}\label{genre-study}

Steam genre labels are sometimes inconsistent, so we use a grouped genre
taxonomy created for this project (e.g., action, RPG, strategy,
platformer, etc.). Each successful game is mapped into one or more of
these grouped genres using its Genres/Tags/Categories. The Genres have
been described in a previous section of the document.

Before adopting this approach, we initially attempted to mine
association rules directly predicting success, by fixing the right-hand
side of the rules to \texttt{successful\ =\ TRUE}.

However, this produced obscure and highly specific combinations with
limited generality: many rules were driven by niche tag mixes or small
subsets of games, and they did not reflect the kinds of genre patterns
seen in widely recognized successful indie titles.

For that reason, we switched to a more interpretable strategy: First
filter the dataset to successful indie games, and then mine frequent
itemsets (genre combinations) with sufficient support inside this
subset.

This approach still answers our question: \emph{Amongng successful
games, what genre combinations are most common?}

\subsubsection{Most common genre combinations (frequent
itemsets)}\label{most-common-genre-combinations-frequent-itemsets}

The table below lists the most frequent genre combinations among
successful games (support = proportion of successful games containing
that combination).
\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-30-1.pdf}}
\#\#\# Genre prevalence
\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-31-1.pdf}}
\#\#\# Conclussions from genres The grouped genre counts show a highly
concentrated distribution: successful indie games most frequently fall
under action and casual, followed by a second tier including RPG,
tabletop/puzzle, strategy, and simulation. This suggests that, within
the successful segment, many games belong to genres that are either
broad and audience-friendly (action/casual), or built around deep
progression and replayability (RPG/strategy/simulation/tabletop).

Looking at frequent genre combinations (Eclat), the strongest result is
the pairing \{action, casual\}, which appears in roughly one quarter of
successful games. More generally, casual acts as a ``bridge'' genre: it
appears in many of the top combinations (e.g., tabletop + casual,
simulation + casual, strategy + casual, and RPG + casual). This
indicates that many successful indie games mix a core genre identity
with accessible design traits (short sessions or low entry difficulty).

The second major pattern is that action combines well with several
popular genres: action + RPG, action + simulation, action + strategy,
action + shooter, and action + platformer all appear as frequent
itemsets. This highlights a typical indie design strategy: start from a
strong core action loop and enrich it with complementary systems such as
progression (RPG), management (simulation/strategy), or movement
challenges (platformer).

\subsection{Mechanics study}\label{mechanics-study}

Mechanics are stored as list of tags (e.g., resource\_management,
procedural, narrative, card/deckbuilding, etc.) in the steam dataset so
they are first one-hot encoded in a binary manner so the apriori
algorithm can be executed over them. Instead of only asking ``which
mechanics are common?'', we also ask: \emph{Given a genre combination,
which mechanics are most strongly associated with it?}

We mine association rules of the form: * LHS (antecedent): genre
group(s) * RHS (consequent): mechanic group

Rules are ranked by lift to highlight mechanics that occur more often
than expected within a genre context. The support is set to
\texttt{0.01} and confidence to \texttt{0.3}. Higher values fail to find
interesting relationships in the data.

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-33-1.pdf}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.6528}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1111}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1528}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.0833}}@{}}
\caption{Top genre-\textgreater mechanic rules among successful indie
games (ranked by lift)}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Rule (Genres -\textgreater{} Mechanic)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Support
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Confidence
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Lift
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Rule (Genres -\textgreater{} Mechanic)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Support
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Confidence
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Lift
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\{simulation,strategy\} =\textgreater{} \{resource\_management\} & 0.045
& 0.393 & 3.746 \\
\{action,strategy\} =\textgreater{} \{resource\_management\} & 0.044 &
0.318 & 3.029 \\
\{action,simulation\} =\textgreater{} \{resource\_management\} & 0.045 &
0.310 & 2.950 \\
\{action,platformer\} =\textgreater{} \{exploration\} & 0.059 & 0.483 &
2.088 \\
\{action,tabletop\} =\textgreater{} \{exploration\} & 0.050 & 0.434 &
1.876 \\
\{action,RPG\} =\textgreater{} \{exploration\} & 0.053 & 0.380 &
1.641 \\
\end{longtable}

\subsubsection{Conclussions from genres and mechanic
rules}\label{conclussions-from-genres-and-mechanic-rules}

A first clear pattern is the strength of resource management inside
strategy/simulation hybrids. The rule \{simulation, strategy\}
-\textgreater{} \{resource\_management\} has the highest lift (around
3.75), meaning that management-oriented mechanics are several times more
likely than expected when a game sits at the intersection of these
genres. Similar high-lift rules also appear for \{action, strategy\} and
\{action, simulation\}, suggesting that successful hybrids often combine
an action layer with systems such as crafting, automation, building, or
economy loops.

A second pattern is that exploration frequently complements
action-driven genres. Rules such as \{action, platformer\}
-\textgreater{} \{exploration\}, \{action, tabletop\} -\textgreater{}
\{exploration\}, and \{action, RPG\} -\textgreater{} \{exploration\}
show relatively high confidence, indicating that when successful games
blend action with movement/progression, they often reinforce the
experience through discovery loops (new areas, loot, dungeons,
collectables, or open-ended progression paths).

Overall, the results support a practical conclusion: successful indie
games often rely on a core genre identity and then amplify engagement
through a matching mechanic; management systems for strategy/simulation
hybrids, and exploration loops for action-driven combinations. These
associations do not prove causality, but they highlight combinations
that repeatedly co-occur among successful titles and can reduce design
risk by aligning with common audience expectations.

\subsection{Game characteristics
study}\label{game-characteristics-study}

Characteristics are captured from Steam categories/tags that describe
presentation and play modes (e.g., 2D/3D, first-person/third-person,
singleplayer/co-op, VR). We mine frequent characteristic combinations
using Eclat.

\subsubsection{Top characteristic
combinations}\label{top-characteristic-combinations}

\begin{longtable}[]{@{}llr@{}}
\caption{Top characteristic combinations among successful indie
games}\tabularnewline
\toprule\noalign{}
& Characteristic combination & Support \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
& Characteristic combination & Support \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
7 & \{Co-op,PvP\} & 0.0529 \\
5 & \{Massively Multiplayer,PvP\} & 0.0165 \\
6 & \{Massively Multiplayer,Co-op\} & 0.0117 \\
4 & \{Massively Multiplayer,Co-op,PvP\} & 0.0092 \\
2 & \{VR Only,PvP\} & 0.0055 \\
3 & \{VR Only,Co-op\} & 0.0044 \\
1 & \{VR Only,Co-op,PvP\} & 0.0026 \\
\end{longtable}

\subsubsection{Conclusions from
characteristics}\label{conclusions-from-characteristics}

The most frequent characteristic combinations in the successful subset
are primarily multiplayer-focused, especially the pairing \{Co-op, PvP\}
(support ≈ 0.053). This suggests that, among successful indie games that
include multiplayer features, a common design choice is to combine
collaboration and competition within the same title.

We also observe VR Only appearing in the top combinations but with low
support, suggesting that VR-exclusive successful games exist but
represent a niche segment compared with traditional PC titles. A
plausible explanation is that the VR market offers fewer alternatives
overall, so the relatively small number of VR-only titles can capture a
larger share of VR players and reach the engagement thresholds needed to
be labeled as successful in our proxy, which makes VR-only features show
up among the top itemsets.

Overall, characteristics appear to matter mainly as experience
modifiers: multiplayer modes (co-op/PvP) are recurring patterns among
successful games, while more specialized formats (like VR-only) are less
common.

\#\#Pricing and owners Finally, we explore whether price is related to
estimated owners. We initially attempted to approach this with a simple
scatter plot which ended up hard to interpret due to heavy overlap and
the long-tail nature of owners. Instead the best analysis technique has
been running a multivariate regression on non-free games and studying
the weights.

\subsubsection{Multivariate regression}\label{multivariate-regression}

A raw relationship between price and owners can be misleading because
both variables are correlated with other factors. To reduce this bias,
we estimate a multivariate regression on paid games only (price
\textgreater{} 0), controlling for: * \textbf{Review volume}
(addittional approximate for audience size) * \textbf{Rating quality}
(proxy for perceived value) * \textbf{Recommendations} (proxy for
engagement) * \textbf{DLC count and language count} (rough indicators of
production scope)

The coefficient of log-price can be interpreted as the partial
association between price and owners after accounting for these
variables.

The price has been capped at 90 euros and games above that price have
been removed since those aren't realistic representations of indie
games.

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Multivariate regression coefficients (paid games
only)}\tabularnewline
\toprule\noalign{}
Variable & Estimate & Std. Error & t value & p value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Variable & Estimate & Std. Error & t value & p value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
log\_price & -0.1027 & 0.0097 & -10.55 & 0.00000 \\
log\_reviews & 0.6396 & 0.0107 & 59.66 & 0.00000 \\
pct\_pos\_total & -0.0058 & 0.0004 & -13.96 & 0.00000 \\
log\_recs & -0.0155 & 0.0059 & -2.62 & 0.00877 \\
dlc\_count & 0.0003 & 0.0004 & 0.83 & 0.40600 \\
languages\_count & -0.0400 & 0.0005 & -79.03 & 0.00000 \\
\end{longtable}

\begin{longtable}[]{@{}lr@{}}
\caption{Variance Inflation Factors (VIF) for multicollinearity
diagnosis}\tabularnewline
\toprule\noalign{}
Variable & VIF \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Variable & VIF \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
log\_reviews & 6.79 \\
log\_recs & 6.69 \\
log\_price & 1.12 \\
pct\_pos\_total & 1.04 \\
languages\_count & 1.02 \\
dlc\_count & 1.00 \\
\end{longtable}

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Standardized coefficients}\tabularnewline
\toprule\noalign{}
Variable & Std\_Estimate & Std. Error & t value & p value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Variable & Std\_Estimate & Std. Error & t value & p value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
log\_reviews & 0.648 & 0.011 & 59.66 & 0.00000 \\
languages\_count & -0.332 & 0.004 & -79.03 & 0.00000 \\
pct\_pos\_total & -0.059 & 0.004 & -13.96 & 0.00000 \\
log\_price & -0.047 & 0.004 & -10.55 & 0.00000 \\
log\_recs & -0.028 & 0.011 & -2.62 & 0.00877 \\
dlc\_count & 0.003 & 0.004 & 0.83 & 0.40600 \\
\end{longtable}

The VIF table provides an explicit check for multicollinearity. When VIF
values are elevated, predictors overlap strongly (for example, review
volume and recommendations both reflect visibility and player
engagement). In that situation, individual coefficients should be
interpreted cautiously: their signs and magnitudes can shift because the
model is separating very similar signals.

Multicollinearity does not affect the interpretation of price, since
log\_price has VIF 1.12. Therefore, the negative coefficient of price
can be interpreted as a stable partial relationship: higher prices are
associated with slightly fewer owners, although the magnitude is small
compared to visibility signals such as review volume.

After controlling for closely related visibility/quality variables,
price has at most a small partial association with owners. This suggests
that in the indie market, audience size is driven more by
discoverability and perceived value (captured by reviews and engagement
signals) than by price alone.

\subsection{Conclussion}\label{conclussion}

\section{Can a single game have enough influence to make other games
have its
tag?}\label{can-a-single-game-have-enough-influence-to-make-other-games-have-its-tag}

\subsection{Game study: Slay the Spire (Roguelike
Deckbuilder)}\label{game-study-slay-the-spire-roguelike-deckbuilder}

\begin{verbatim}
## [1] "Slay the Spire"
\end{verbatim}

\begin{verbatim}
## [1] "2019-01-23"
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = freq ~ t + post + t:post, data = ts_slayTheSpire)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.2087 -0.4368 -0.1021  0.5213 11.1710 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.529412   0.403337   1.313 0.191278    
## t            0.007563   0.008292   0.912 0.363151    
## post        -2.164115   0.599569  -3.609 0.000414 ***
## t:post       0.156203   0.013316  11.731  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.876 on 154 degrees of freedom
## Multiple R-squared:  0.7433, Adjusted R-squared:  0.7383 
## F-statistic: 148.7 on 3 and 154 DF,  p-value: < 2.2e-16
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-41-1.pdf}}

\begin{verbatim}
## 
## Call:
## lm(formula = freq ~ t + post + t:post, data = ts_slayTheSpire)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.2087 -0.4368 -0.1021  0.5213 11.1710 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.529412   0.403337   1.313 0.191278    
## t            0.007563   0.008292   0.912 0.363151    
## post        -2.164115   0.599569  -3.609 0.000414 ***
## t:post       0.156203   0.013316  11.731  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.876 on 154 degrees of freedom
## Multiple R-squared:  0.7433, Adjusted R-squared:  0.7383 
## F-statistic: 148.7 on 3 and 154 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = freq ~ t + post + t:post, data = ts_global)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -427.10  -66.85   -1.87   81.84  474.64 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  630.1863    28.6368  22.006  < 2e-16 ***
## t              8.6137     0.5887  14.631  < 2e-16 ***
## post        -291.8553    42.5691  -6.856 1.61e-10 ***
## t:post         6.3578     0.9454   6.725 3.24e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 133.2 on 154 degrees of freedom
## Multiple R-squared:  0.9061, Adjusted R-squared:  0.9042 
## F-statistic: 495.2 on 3 and 154 DF,  p-value: < 2.2e-16
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-45-1.pdf}}

\begin{verbatim}
## 
## Call:
## lm(formula = freq ~ t * post * series, data = combined)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -427.10   -4.05   -0.12    4.33  474.64 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(>|t|)    
## (Intercept)       630.1863    20.2513  31.118  < 2e-16 ***
## t                   8.6137     0.4163  20.689  < 2e-16 ***
## post             -291.8553    30.1039  -9.695  < 2e-16 ***
## seriestag        -629.6569    28.6396 -21.986  < 2e-16 ***
## t:post              6.3578     0.6686   9.509  < 2e-16 ***
## t:seriestag        -8.6061     0.5888 -14.617  < 2e-16 ***
## post:seriestag    289.6912    42.5733   6.805 5.29e-11 ***
## t:post:seriestag   -6.2015     0.9455  -6.559 2.29e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 94.18 on 308 degrees of freedom
## Multiple R-squared:  0.9488, Adjusted R-squared:  0.9476 
## F-statistic: 815.6 on 7 and 308 DF,  p-value: < 2.2e-16
\end{verbatim}

\subsection{Game Study: The Binding Of Isaac + The Binding Of Isaac
Rebirth
(Roguelike)}\label{game-study-the-binding-of-isaac-the-binding-of-isaac-rebirth-roguelike}

\begin{verbatim}
## [1] "The Binding of Isaac"
\end{verbatim}

\begin{verbatim}
## [1] "2011-09-28"
\end{verbatim}

\begin{verbatim}
## [1] "The Binding of Isaac: Rebirth"
\end{verbatim}

\begin{verbatim}
## [1] "2014-11-04"
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-48-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-50-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-51-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-53-1.pdf}}

\begin{verbatim}
## [1] "Terraria"
\end{verbatim}

\begin{verbatim}
## [1] "2011-05-16"
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{SteamSuccessfulIndieGamesStudy_files/figure-latex/unnamed-chunk-55-1.pdf}}

\end{document}
